CXX = g++
CXXFLAGS = -std=c++17 -Wall -g
LDFLAGS = -lncurses -lpthread
TARGET = file_manager
SRCS = codigo.cpp
OBJS = $(SRCS:.cpp=.o)

$(TARGET): $(OBJS)
  $(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

%.o: %.cpp
  $(CXX) $(CXXFLAGS) -c $< -o $@

clean:
  rm -f $(OBJS) $(TARGET)

run: $(TARGET)
  ./$(TARGET)

.PHONY: clean run
